### ISSUE TITLE
`can't modify frozen String: ""` errors when using Ruby 2.7

### ISSUE THREAD

**Issue by LocoDelAssembly** [inukshuk/citeproc-ruby#71] opened 2019-12-26 18:30 UTC
When using Ruby 2.7 there are `can't modify frozen String: ""` errors that I was unable to resolve:
https://travis-ci.org/LocoDelAssembly/citeproc-ruby/jobs/629710730#L13932

I've made an [attempt](https://github.com/LocoDelAssembly/citeproc-ruby/commit/382b44cd8171d6f8276ec54f6e54fbbfb3e96ac9) to solve this but resulted in moving the problem to cucumber test suite and breaking all ruby versions: https://travis-ci.org/LocoDelAssembly/citeproc-ruby/builds/629716123

I anyone could give me some hints on where the problem could be I may try to resolve it and contribute a pull request.

Thanks

**Comment by inukshuk** [comment] 2020-01-07 20:18
I think we can skip this for empty strings for now (the issue is that these default strings are converted from nils, which returns the same frozen empty string on 2.7).

**Comment by rbq** [comment] 2020-01-20 09:34
This seems to be fixed in master, but hasn't been released yet?

**Comment by inukshuk** [comment] 2020-01-20 10:36
Yes, thanks for the reminder! Pushed to RubyGems just now.

**Closed by inukshuk** 2020-01-20 10:36 UTC

**Comment by rbq** [comment] 2020-01-21 10:15
Thanks a lot!
